### Send PUT request with json body
PUT http://localhost:8080/developers/tester1
Content-Type: application/json

{
  "developerLevel": "JUNGNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 6
}