### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 12,
  "memberId": "tester1",
  "name": "test1",
  "age": 32
}